# **üßë‚ÄçüíªEXTRACTION FROM DATAFRME**

In [2]:
# LOADING DATA:
import pandas as pd
DATA=pd.read_csv(r"C:\Users\Nagesh Agrawal\OneDrive\Desktop\PANDAS\z_DATA\archive (1)\2019-Nov.csv")

In [5]:
# SINGLE COLUMN:
DATA["brand"]

0               NaN
1               NaN
2               pnb
3          jessnail
4               NaN
             ...
4635832         NaN
4635833     beautix
4635834        kims
4635835         NaN
4635836      rasyan
Name: brand, Length: 4635837, dtype: object

In [9]:
# MULTIPLE COLUMNS:
DATA[["brand","price"]]

            brand  price
0             NaN   0.32
1             NaN   2.38
2             pnb  22.22
3        jessnail   3.16
4             NaN   3.33
...           ...    ...
4635832       NaN   4.76
4635833   beautix   9.37
4635834      kims  31.10
4635835       NaN   2.86
4635836    rasyan   3.76

[4635837 rows x 2 columns]

In [20]:
# SELECTING ROW BY LOC FUNCTION: BY INDEX OF ROW 
DATA.loc[0]

event_time                    2019-11-01 00:00:02 UTC
event_type                                       view
product_id                                    5802432
category_id                       1487580009286598681
category_code                                     NaN
brand                                             NaN
price                                            0.32
user_id                                     562076640
user_session     09fafd6c-6c99-46b1-834f-33527f4de241
Name: 0, dtype: object

In [17]:
DATA.loc[0:5]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:02 UTC,view,5802432,1487580009286598681,NaN,NaN,0.32,562076640,09fafd6c-6c99-46b1-834f-33527f4de241
1,2019-11-01 00:00:09 UTC,cart,5844397,1487580006317032337,NaN,NaN,2.38,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb
2,2019-11-01 00:00:10 UTC,view,5837166,1783999064103190764,NaN,pnb,22.22,556138645,57ed222e-a54a-4907-9944-5a875c2d7f4f
3,2019-11-01 00:00:11 UTC,cart,5876812,1487580010100293687,NaN,jessnail,3.16,564506666,186c1951-8052-4b37-adce-dd9644b1d5f7
4,2019-11-01 00:00:24 UTC,remove_from_cart,5826182,1487580007483048900,NaN,NaN,3.33,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb
5,2019-11-01 00:00:24 UTC,remove_from_cart,5826182,1487580007483048900,NaN,NaN,3.33,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb

In [14]:
# SELECTING ROW BY ILOC FUNCTION: BY INDEX OF ROW 
DATA.iloc[0]

event_time                    2019-11-01 00:00:02 UTC
event_type                                       view
product_id                                    5802432
category_id                       1487580009286598681
category_code                                     NaN
brand                                             NaN
price                                            0.32
user_id                                     562076640
user_session     09fafd6c-6c99-46b1-834f-33527f4de241
Name: 0, dtype: object

In [21]:
DATA.iloc[0:5] #0 to 4 only .

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:02 UTC,view,5802432,1487580009286598681,NaN,NaN,0.32,562076640,09fafd6c-6c99-46b1-834f-33527f4de241
1,2019-11-01 00:00:09 UTC,cart,5844397,1487580006317032337,NaN,NaN,2.38,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb
2,2019-11-01 00:00:10 UTC,view,5837166,1783999064103190764,NaN,pnb,22.22,556138645,57ed222e-a54a-4907-9944-5a875c2d7f4f
3,2019-11-01 00:00:11 UTC,cart,5876812,1487580010100293687,NaN,jessnail,3.16,564506666,186c1951-8052-4b37-adce-dd9644b1d5f7
4,2019-11-01 00:00:24 UTC,remove_from_cart,5826182,1487580007483048900,NaN,NaN,3.33,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb

In [36]:
# CONDITIONAL SELECTION:
DATA[DATA["price"]>327]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
2809483,2019-11-21 11:22:00 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,554212419,42f9fcd2-d207-1bfe-816c-22b49f1511aa
2815661,2019-11-21 11:50:46 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,574388782,948b84fd-83c1-4782-abfa-613cdd6775cc
2833486,2019-11-21 13:18:42 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,574388782,2b003d10-8b8f-4801-981d-c32902170872
2854007,2019-11-21 15:07:45 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,533560354,ab82d077-c051-44f2-9eee-f934f0ef88bc
2854097,2019-11-21 15:08:13 UTC,cart,5906221,1487580006300255120,NaN,strong,327.78,533560354,ab82d077-c051-44f2-9eee-f934f0ef88bc
...,...,...,...,...,...,...,...,...,...
4009862,2019-11-27 18:43:59 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,534680076,2a7dd941-bc92-44eb-b488-a120b6bee445
4012126,2019-11-27 18:59:45 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,446734124,2011afc2-7228-42ac-b061-60452b22fc67
4030902,2019-11-27 21:07:37 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,323241708,d03295ab-8c57-4aa2-b2a0-45ecf39a0ffb
4031759,2019-11-27 21:14:38 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,577886304,dc5f6b62-4abd-4b8a-a8f5-3b36a01bfabb
4040899,2019-11-27 22:51:33 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,577914521,6ed7c01e-0b0b-46ce-9754-19d0af43f248

In [37]:
# MULTIPLE COMDITIONS:
DATA[(DATA["price"]>327) & (DATA["brand"]=="strong")]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
2809483,2019-11-21 11:22:00 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,554212419,42f9fcd2-d207-1bfe-816c-22b49f1511aa
2815661,2019-11-21 11:50:46 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,574388782,948b84fd-83c1-4782-abfa-613cdd6775cc
2833486,2019-11-21 13:18:42 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,574388782,2b003d10-8b8f-4801-981d-c32902170872
2854007,2019-11-21 15:07:45 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,533560354,ab82d077-c051-44f2-9eee-f934f0ef88bc
2854097,2019-11-21 15:08:13 UTC,cart,5906221,1487580006300255120,NaN,strong,327.78,533560354,ab82d077-c051-44f2-9eee-f934f0ef88bc
...,...,...,...,...,...,...,...,...,...
4009862,2019-11-27 18:43:59 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,534680076,2a7dd941-bc92-44eb-b488-a120b6bee445
4012126,2019-11-27 18:59:45 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,446734124,2011afc2-7228-42ac-b061-60452b22fc67
4030902,2019-11-27 21:07:37 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,323241708,d03295ab-8c57-4aa2-b2a0-45ecf39a0ffb
4031759,2019-11-27 21:14:38 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,577886304,dc5f6b62-4abd-4b8a-a8f5-3b36a01bfabb
4040899,2019-11-27 22:51:33 UTC,view,5906221,1487580006300255120,NaN,strong,327.78,577914521,6ed7c01e-0b0b-46ce-9754-19d0af43f248

In [45]:
DATA.loc[:5,"brand"]

0         NaN
1         NaN
2         pnb
3    jessnail
4         NaN
5         NaN
Name: brand, dtype: object

In [53]:
DATA.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

In [52]:
DATA.iloc[:5,5]

0         NaN
1         NaN
2         pnb
3    jessnail
4         NaN
Name: brand, dtype: object

In [48]:
# slicing:
DATA.loc[:5,["price","brand"]]

   price     brand
0   0.32       NaN
1   2.38       NaN
2  22.22       pnb
3   3.16  jessnail
4   3.33       NaN
5   3.33       NaN

In [59]:
DATA[DATA.duplicated()]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
5,2019-11-01 00:00:24 UTC,remove_from_cart,5826182,1487580007483048900,NaN,NaN,3.33,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb
91,2019-11-01 00:06:22 UTC,remove_from_cart,5826980,1487580005671109489,NaN,masura,3.95,556138645,57ed222e-a54a-4907-9944-5a875c2d7f4f
161,2019-11-01 00:13:16 UTC,remove_from_cart,5749153,1487580007592100809,NaN,NaN,0.22,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf
163,2019-11-01 00:13:17 UTC,remove_from_cart,5749156,1487580007592100809,NaN,NaN,0.22,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf
174,2019-11-01 00:13:39 UTC,remove_from_cart,5804460,1783999063574708423,NaN,bluesky,19.05,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf
...,...,...,...,...,...,...,...,...,...
4635730,2019-11-30 23:56:08 UTC,remove_from_cart,5700047,1487580009286598681,NaN,runail,0.40,579966747,1512be50-d0fd-4a92-bcd8-3ea3943f2a3b
4635773,2019-11-30 23:57:31 UTC,cart,5670333,1487580006484804506,NaN,NaN,11.03,494077766,c99a50e8-2fac-4c4d-89ec-41c05f114554
4635824,2019-11-30 23:59:24 UTC,remove_from_cart,5608703,1487580005553668971,NaN,NaN,9.52,566513990,b5053009-b3c4-4581-b05f-6199d1a2037e
4635827,2019-11-30 23:59:25 UTC,remove_from_cart,5810080,1487580005268456287,NaN,irisk,6.51,566513990,b5053009-b3c4-4581-b05f-6199d1a2037e
4635829,2019-11-30 23:59:27 UTC,remove_from_cart,5801131,1487580005486560104,NaN,irisk,3.65,566513990,b5053009-b3c4-4581-b05f-6199d1a2037e

In [63]:
DATA[DATA.duplicated(keep=False)]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
4,2019-11-01 00:00:24 UTC,remove_from_cart,5826182,1487580007483048900,NaN,NaN,3.33,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb
5,2019-11-01 00:00:24 UTC,remove_from_cart,5826182,1487580007483048900,NaN,NaN,3.33,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb
90,2019-11-01 00:06:22 UTC,remove_from_cart,5826980,1487580005671109489,NaN,masura,3.95,556138645,57ed222e-a54a-4907-9944-5a875c2d7f4f
91,2019-11-01 00:06:22 UTC,remove_from_cart,5826980,1487580005671109489,NaN,masura,3.95,556138645,57ed222e-a54a-4907-9944-5a875c2d7f4f
160,2019-11-01 00:13:16 UTC,remove_from_cart,5749153,1487580007592100809,NaN,NaN,0.22,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf
...,...,...,...,...,...,...,...,...,...
4635824,2019-11-30 23:59:24 UTC,remove_from_cart,5608703,1487580005553668971,NaN,NaN,9.52,566513990,b5053009-b3c4-4581-b05f-6199d1a2037e
4635826,2019-11-30 23:59:25 UTC,remove_from_cart,5810080,1487580005268456287,NaN,irisk,6.51,566513990,b5053009-b3c4-4581-b05f-6199d1a2037e
4635827,2019-11-30 23:59:25 UTC,remove_from_cart,5810080,1487580005268456287,NaN,irisk,6.51,566513990,b5053009-b3c4-4581-b05f-6199d1a2037e
4635828,2019-11-30 23:59:27 UTC,remove_from_cart,5801131,1487580005486560104,NaN,irisk,3.65,566513990,b5053009-b3c4-4581-b05f-6199d1a2037e
4635829,2019-11-30 23:59:27 UTC,remove_from_cart,5801131,1487580005486560104,NaN,irisk,3.65,566513990,b5053009-b3c4-4581-b05f-6199d1a2037e

In [58]:
DATA[DATA.isna()]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
4635832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4635833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4635834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4635835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4635836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Awesome! Here's your **decorative version** ‚Äî same content but more stylish, clean, and colorful-looking (I'll suggest symbols, boxes, and neat sections):

---

# üìö `.iloc` Selection

---

### ‚ú® Extracting all Rows and single column
```python
df.iloc[:, 1]
```

---

### ‚ú® Extracting all Rows and range of columns only
```python
df.iloc[:, 1:3]
```

---

### ‚ú® Extracting all Rows and single column
```python
df.iloc[:, 1]
```

---

### ‚ú® Extracting top 5 Rows and range of columns only
```python
df.iloc[0:5, 1:4]
```

---

### ‚ú® Extracting top 5 Rows and single column
```python
df.iloc[0:5, 1]
```

---

### ‚ú® Extracting all columns and single Row
```python
df.iloc[2, :]
```
or
```python
df.iloc[[2]]
```

---

### ‚ú® Extracting random records by using index parameter
```python
df.iloc[[0, 2, 4]]
```
or
```python
df.iloc[[0, 2, 4], :]
```

---

### ‚ú® Skipped Rows (start:stop:endvalue/stepvalue)
```python
df.iloc[0:10:2]
```

---

# üìö `.loc` Selection

---

### ‚ú® Accessing single value
```python
df.loc['rowlabel', 'columnlabel']
```

---

### ‚ú® Accessing single Row
```python
df.loc['rowlabel']
```

---

### ‚ú® Accessing multiple Rows
```python
df.loc[['a', 'b']]
```

---

### ‚ú® Accessing single Column
```python
df.loc[:, 'colname']
```

---

### ‚ú® Accessing multiple Columns
```python
df.loc[:, ['name', 'city']]
```

---

### ‚ú® Accessing multiple Rows and Columns
```python
df.loc[['rowlabel1', 'rowlabel2'], ['columnlabel1', 'columnlabel2']]
```

---